USE KutdusovIlshat;
GO

CREATE TABLE Production (
ModelName VARCHAR(10) NOT NULL PRIMARY KEY,
ProductionName VARCHAR(10) NOT NULL,
ReleaseStart DATETIME NOT NULL,
ReleaseStop DATETIME NOT NULL
);

CREATE TABLE Car (
VIN INT NOT NULL PRIMARY KEY,
Color VARCHAR(10) NOT NULL,
Release DATETIME NOT NULL,
Mileage INT NOT NULL DEFAULT 0,
Production VARCHAR(10) NOT NULL,
Client INT NOT NULL,
Tariff INT NOT NULL DEFAULT 1,
);

CREATE TABLE Client (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FirstName VARCHAR(20) NOT NULL,
LastName VARCHAR(20) NOT NULL,
PhoneNumber	INT NOT NULL,
);

CREATE TABLE Tariff (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
TariffName VARCHAR(20) NOT NULL,
Cost INT NOT NULL DEFAULT 1000,
Info VARCHAR(250) NOT NULL DEFAULT 'No bonuses'
);